# Generated by Django 3.0.5 on 2020-05-07 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('minute', models.IntegerField(verbose_name='Минуты')),
                ('hour', models.IntegerField(verbose_name='Часы')),
                ('weekday', models.CharField(max_length=15, verbose_name='День недели')),
                ('day', models.IntegerField(verbose_name='День месяца')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('quarter', models.IntegerField(verbose_name='Квартал')),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Время и дата',
                'verbose_name_plural': 'Времена и даты',
            },
        ),
        migrations.CreateModel(
            name='PortCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PortCountry', verbose_name='Страна')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(max_length=15, verbose_name='Тип')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Порт',
                'verbose_name_plural': 'Порты',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('departure_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_port', to='core.Port', verbose_name='Порт отправления')),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_port', to='core.Port', verbose_name='Порт назначения')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='VesselBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год постройки судна',
                'verbose_name_plural': 'Года постройки судов',
            },
        ),
        migrations.CreateModel(
            name='VesselFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flag', models.CharField(max_length=50, verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Флаг судна',
                'verbose_name_plural': 'Флаги судов',
            },
        ),
        migrations.CreateModel(
            name='VesselType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип судна',
                'verbose_name_plural': 'Типы судов',
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('mmsi', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='MMSI')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.VesselType', verbose_name='Тип')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.VesselFlag', verbose_name='Флаг')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.VesselBuild', verbose_name='Год постройки')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('imo', models.IntegerField(verbose_name='IMO')),
                ('call_sign', models.CharField(max_length=10, verbose_name='Позывной')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('grt', models.IntegerField(verbose_name='Грузоподъемность')),
                ('dwt', models.IntegerField(verbose_name='Дедвейт')),
            ],
            options={
                'verbose_name': 'Судно',
                'verbose_name_plural': 'Суда',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Route', verbose_name='Маршрут')),
                ('mmsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Vessel', verbose_name='MMSI')),
                ('departure_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_date', to='core.Date',
                                   verbose_name='Дата отправления')),
                ('arrival_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arr_date', to='core.Date',
                                   verbose_name='Дата прибытия')),
                ('time_in_port', models.IntegerField(verbose_name='Время в порту')),
                ('fuel_costs', models.IntegerField(verbose_name='Затраты на топливо')),
                ('crew_costs', models.IntegerField(verbose_name='Затраты на экипаж')),
                ('port_charges', models.IntegerField(verbose_name='Портовые расходы')),
                ('insurance_costs', models.IntegerField(verbose_name='Затраты на страховку')),
                ('total_costs', models.IntegerField(verbose_name='Сумма затрат')),
                ('cargo_income', models.IntegerField(verbose_name='Доход от перевозки груза')),
                ('net_total_freight', models.IntegerField(verbose_name='Чистый суммарный фрахт')),
                ('voyage_profit', models.IntegerField(verbose_name='Прибыль за рейс')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
    ]
